iperf2: Fix compiler error for abs(time_t) without CONFIG_SYSTEM_TIME64
|                  | time_t = int64_t | time_t = uint32_t  |
| :--------------: | :--------------: | :----------------: |
|      abs(time_t) | -Wabsolute-value | ambiguous overload |
|     labs(time_t) | -Wabsolute-value | -Wabsolute-value   |
|    llabs(time_t) |        OK        | -Wabsolute-value   |
| abs(int(time_t)) |        OK        |         OK         |

Errors:

With time_t = int64_t:
iperf2/src/Server.cpp:606:7: warning: absolute value function 'abs' given an argument of type 'long long' but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
        if ((abs(now.getSecs() - mSettings->sent_time.tv_sec)) > MAXDIFFTIMESTAMPSECS) {
             ^

With time_t = uint32_t:
iperf2/src/Server.cpp:606:17: error: call of overloaded ‘abs(time_t)’ is ambiguous
  606 |         if ((abs(now.getSecs() - mSettings->sent_time.tv_sec)) > MAXDIFFTIMESTAMPSECS) {
      |              ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

- If we change to `labs` or `llabs`:
  warning: taking the absolute value of unsigned type 'unsigned int' has no effect [-Wabsolute-value]

Signed-off-by: Zhe Weng <wengzhe@xiaomi.com>